### ISSUE TITLE
Преобразовать в else if

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/SportMaster#2]
https://github.com/NailMukhametshin/SportMaster/blob/85c775739f88e24ea9cacf1bc46ba0e3b05f8635/src/main/java/ru/itpark/SportMaster.java#L19-L27

Вместо 
```java
else {
   if (...) {
   } else {
   }
```

Используйте
```java
else if (...) {
} else {
}
```

А ещё лучше short circuit return.

**Comment by NailMukhametshin** [comment]
@coursar, исправил в 7814384ee3d5caf8227c2584395c4ed4bd71e1af
После долгих раздумий упростил алгоритм и применил "else if"
https://github.com/NailMukhametshin/SportMaster/blob/7814384ee3d5caf8227c2584395c4ed4bd71e1af/src/main/java/ru/itpark/SportMaster.java#L18-L23
