### ISSUE TITLE
Имена переменных - с маленькой буквы

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/SportMaster#3]
https://github.com/NailMukhametshin/SportMaster/blob/85c775739f88e24ea9cacf1bc46ba0e3b05f8635/src/test/java/ru/itpark/SportMasterTest.java#L12

**Comment by NailMukhametshin** [comment]
@coursar, исправил в 7814384ee3d5caf8227c2584395c4ed4bd71e1af, во всех 4х строках.
https://github.com/NailMukhametshin/SportMaster/blob/7814384ee3d5caf8227c2584395c4ed4bd71e1af/src/test/java/ru/itpark/SportMasterTest.java#L13

**Comment by coursar** [comment]
@NailMukhametshin, старайтесь одним коммиттом делать одну логическую вещь, а то в этом коммите вы и имена переменных поменяли и условие переделали.
