### ISSUE TITLE
Бонус при нулевой истории

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/SportMaster#4]
Что должно быть результатом этого теста?
```java
        {
            SportMaster sportMaster = new SportMaster();
            int cashBack = sportMaster.calculateCashBack(0, 1_000);
            assertEquals(0, cashBack);
        }
```

**Comment by NailMukhametshin** [comment]
@coursar, исправлено в 7814384ee3d5caf8227c2584395c4ed4bd71e1af, 
а именно подправил формулу и привел тест с нулевым балансом.
https://github.com/NailMukhametshin/SportMaster/blob/7814384ee3d5caf8227c2584395c4ed4bd71e1af/src/main/java/ru/itpark/SportMaster.java#L15
https://github.com/NailMukhametshin/SportMaster/blob/7814384ee3d5caf8227c2584395c4ed4bd71e1af/src/test/java/ru/itpark/SportMasterTest.java#L12-L16
